name: Build

on:
  push:
    branches:
      - main

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bundle-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run local tests
        if: always()
        run: ./gradlew --no-configuration-cache bundleRelease

      - name: Find APK path
        id: find-apk
        run: |
          echo "Current working directory: $(pwd)"
          find app/build/outputs -name "*.apk" -print -quit
          echo "APK_FILE_PATH_MARKER: $(find app/build/outputs -name "*.apk" -print -quit)" 

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: ${{ steps.find-apk.outputs.apk_path }}

  unit-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Module Coverage
        run: ./gradlew debugCoverage
      - name: Jacoco Report
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/**/debugCoverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
